# Generated by Django 4.2.11 on 2024-06-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='bank.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_transactions', to='bank.card'),
        ),
    ]
