# Generated by Django 4.2.11 on 2024-06-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cvv2', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
